export const FETCH_LESSONS = "FETCH_LESSONS"
export const FETCH_LESSONS_SUCCESS = "FETCH_LESSONS_SUCCESS"
export const FETCH_LESSONS_FAILURE = "FETCH_LESSONS_FAILURE"

export const FETCH_LESSON_BY_ID = "FETCH_LESSON_BY_ID"
export const FETCH_LESSON_BY_ID_SUCCESS = "FETCH_LESSON_BY_ID_SUCCESS"
export const FETCH_LESSON_BY_ID_FAILURE = "FETCH_LESSON_BY_ID_FAILURE"

export const SEARCH_LESSON = "SEARCH_LESSON"